---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/dependency-review.yml@635f5727c8686b952f53d2fbe1d2e80d2480c831
