---
name: "Dependabot - Auto-merge"

# yamllint disable-line rule:truthy
on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-automerge:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/dependabot-automerge-any.yml@635f5727c8686b952f53d2fbe1d2e80d2480c831
