---
name: "Release Drafter"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/release-drafter.yml@635f5727c8686b952f53d2fbe1d2e80d2480c831
